# API Configuration - Dev Environment
apibaseurl=https://api-dev.demo.com/v1
apiKey=${ABTEST2_API_KEY}

# Agency/Program IDs - Dev
agencyId=U5222222222222222-DEV
programId=8555555555555555-DEV

# XML Namespace
xmlns=http://www.pj.com/api/v1/

# Form/Field IDs - Dev Environment
projectChecklistFormId=8555555555555-DEV
singleLineAttachmentId=15555555555555-DEV
meterNumberDataFieldId=U4444444444444-DEV
meterSetDateDataFieldId=G444444444444-DEV
revisedSiteDiagramAttachmentId=ERRRRRRRRRRRRR-DEV
siteDiagramAttachmentId=9EEEEEEEEEEE-DEV
hostCustomerSectorFieldId=4DDDDDDDDDDDDDD-DEV
inspectionFormId=FFFFFFFFFF-DEV
ahjFormId=FFFFFFFFFF-DEV
applicationFormId=GGGGGGGG-DEV

# File Paths - Dev Environment
attachmentFilePath=/dev/smud456Single Line Drawings
projectsFilePath=/dev/smud456/ProjectsExport
siteDiagramFilePath=/dev/smud123/Site Drawings

# Security Config
hashAlgorithm=HmacSHA1
TOTPReturnDigits=60
