crSourceFolder=/usr/local/apache-tomcat-7.0.53/webapps/Admin_IVR/data/temp
crSourceUsername=tomcat
crSourcePwd=abc1234
crSourcePort=22
crDestinationHosts=10.34.59.80,10.34.59.80
District_IVR= /usr/local/apache-tomcat-7.0.53/webapps/District_IVR/data/english/phrases,/usr/local/apache-tomcat-7.0.53/webapps/Admin_IVR/data/english/phrases
StreamReservoir_IVR=/usr/local/apache-tomcat-7.0.53/webapps/StreamReservoir_IVR/data/english/phrases,/usr/local/apache-tomcat-7.0.53/webapps/Admin_IVR/data/english/phrases
crDestinationUsernames=tomcat,tomcat
crDestinationPasswords=abc1234,abc1234
crDestinationPorts=22,22
sldivrweb01= 10.34.59.80
slpivrweb01=10.34.57.80
slpivrweb03=10.121.24.80