# SmClick3 Package Configuration - Production Environment
# Base LDAP Configuration
ldapSSL=false
ldapUrl=LDAP://ldapt.smud.org/
ldapAdminUser=cn=enroll,ou=special users,o=smud.org,c=us
ldapAdminPassword=password

# Production Environment Configuration
orderNotifDownloadTimeRangeHrs=1
getOmsJobWorkflowURL=https://esbomsprdgw.smud.org/gateway/osi/1.0/job/workflow/transitions
omsGatewayApiKey=omsGatewayApiKey
updateOmsJobWorkflowURL=https://esbomsprdgw.smud.org/gateway/osi/1.0/job/status
districtsForESRITaskView=Service Crews,Line Maintenance / GO
