getAWSTokenUrl=https://fse-na-sb-int01.cloud.clicksoftware.com/so/api/S3Token

getOmsJobWorkflowURL=http://sldvesbomsgw41.smud.org:5555/gateway/osi/1.0/jobWorkflowTransitions
districtsForESRITaskView=Service Crews
baseURL=https://fse-na-sb-int01.cloud.clicksoftware.com/
orderNotifDownloadTimeRangeHrs=1
updateOmsJobWorkflowURL=http://sldvesbomsgw41.smud.org:5555/gateway/osi/1.0/jobStatus
omsGatewayApiKey=omsGatewayApiKey
esriDeviceLocationUrl=https://swdvegiss01.corporate.smud.org/arcgis/rest/services/Hosted/ClickTaskMobile/FeatureServer/0/query
assetDefinedProperties=BEBER,CITY,EQKTU,EQUNR,GROES,HERST,INVNR,LATITUDE,LONGITUDE,MPAR,NAME,PLTXU,SERGE,STATE,STREET,STREET_NUMBER,SYSTEM_STATUS,TPLMA,TPLNR,TYPBZ,USER_STATUS,ZIP_CODE
jmsMessageHourMax=1
sharePointFolder=PhotoTest
sharePointClientSecret=ZXIUwE2aao7LbeEUIoXw+jOpsMGAHr3KDfmpav3HsEZeNWxihEXMeYLOpZ0dSMNWRK17TtJRTqhoQNmhbTvpfA==
objectsBaseURL=https://fse-na-sb-int01.cloud.clicksoftware.com/so/api/objects/
sharePointSite=sites/wpo-upload-testing
equipmentFilePath=//sapifs/rd2/sap_wm/CLICK/Assets/OUT/G_5_6_EqCategories.txt
flocFilePath=//sapifs/rd2/sap_wm/CLICK/Assets/OUT/FuncLocs.txt
sharePointClientID=fb626cc9-d4be-4104-85f7-19d9d9014633
failedRetriesEmailAddress=ana.mederos-aguilar@smud.org
clickEnvironment=smudsb
jmsMessageStaleHourMax=2
failedRetriesReportLocation=//sapifs/RD2/sap_wm/CLICK/ESBReports
districtsForVehicleLocationSync=Substation Maintenance,Line Maintenance / GO
hadoopFolderPath=/tmp/esb/click/
taskFolderPath=/Temp/PG
password=bovCXtyXZb4aLIShCgQMbr26zNHm7jdgdLWSGyHi7Pk=
username=integration@smudsb
