Assign_DG_Number=applicationId
Applicant_Company=applicantCompany
Service_Notification_Number_-_DG_Review=notificationNumber
Inverter_Based_Technology_2=inverterBasedTechnology
Stipend_Payment=stipendPayment
Primary_DG_Technology_3=dgTechnology
PV_Production_Meter_Set_Date=meterSetDate
Operating_Voltage=operatingVoltage
Host_Customer_Sector=customerSector
System_Owner_Company=systemOwnerCompany
Wiring_Configuration=wiringConfiguration
PV_System_Specification_-_As_Built_CEC_Rating=sysRating
PV_System_Specification_-_As_Built_Monthly_Estimated_Production=sysEstMonthlyProd
PV_System_Specification_-_As_Built_Estimated_Production=sysEstAnnualProd
PV_System_Specification_-_As_Built_Design_Factor=sysDesignFactor
PV_System_Specification_-_As_Built_Nameplate_Rating=sysNameplateRating
PV_System_Specification_-_As_Built_Total_Nameplate_Energy_Capacity=sysTotalNameplateCap
Replacement_System_or_Add-on_System=replacementAddOn
Power_Factor_Rating=powerFactorRating
Gross_Nameplate_Rating_kVa=grossNameplateRatingKva
Gross_Nameplate_Rating_kW=grossNameplateRatingKw
Net_Nameplate_Rating=netNameplateRating
PV_Production_Meter_Number=prodMeter1
PV_Production_Meter_Number_2=prodMeter2
Energy_Storage_System_Specs_Count=energyStorageCount
Energy_Storage_System_Specs_Manufacturer=energyStorageManufacturer
Energy_Storage_System_Specs_Model=energyStorageModel
Energy_Storage_System_Specs_Rated_Capacity_/_kWh=energyStorageRatedCap
Energy_Storage_System_Specs_Rated_Output_/_kW_(kW_DC)=energyStorageRatedOutput
Energy_Storage_System_Specs_Continuous_kW_Inverter_Rating_(kW_AC)=energyStorageKwInverterRating
Integrated_Inverter_Yes/No=energyStorageIntgrtInverter
Energy_Storage_System_Info_Manufacturer=energyStorageInfoManu
Energy_Storage_System_Specification_Manufacturer=energyStorageManu
Battery_Storage_Manufacturer_2=battStorageManu2
Battery_Storage_Model_3=battStorageModel3
Battery_Inverter_Manufacturer=battInverterManu
Battery_Inverter_Model_2=battInverterModel2
Battery_Inverter_Specs_v2_Battery_Inverter_Manufacturer=battInverterManuV2
Battery_Inverter_Specs_v2_Battery_Inverter_Model=battInverterModelV2
Rated_Capacity_(kWh)=battInverterRatedCapKwh
Rated_Output_/_kW=battInverterRatedOtptKw
Continuous_KW_Inverter_Rating_2=battInverContKwRating
PV_System_Specification_-_As_Built_Battery_Assigned_Inverter=battAssignedInverter
PV_System_Specification_-_As_Built_Battery_Equipment_Type=battEquipType
PV_System_Specification_-_As_Built_Battery_Manufacturer=battManu
PV_System_Specification_-_As_Built_Battery_Model=battModel
PV_System_Specification_-_As_Built_Battery_Quantity=battQuantity
PV_Nominal_Volt_2=pvNominalVolt
PV_VAR_Priority_2=pvVarPriority
PV_Rec_Inv_Kva_2=pvRecInvKva
PV_Power_Factor_2=pvPowerFactor
PV_Power_Factor_Type_2=pvPowerFactorType
PV_Inv_Setting_Genrtd_2=pvInvSettingGenrtd
PV_Inv_Capacity_Rec_2=pvInvCapacityRec
PV_REC_INV_SETTING_2=pvRecInvSetting
PV_VOLT_SET_0=pvVoltSet0
PV_VOLT_SET_1=pvVoltSet1
PV_VOLT_SET_2=pvVoltSet2
PV_VOLT_SET_3=pvVoltSet3
PV_VOLT_SET_4=pvVoltSet4
PV_VOLT_SET_5=pvVoltSet5
PV_VAR_CAP_SETTING_0=pvVarCapSetting0
PV_VAR_CAP_SETTING_1=pvVarCapSetting1
PV_VAR_CAP_SETTING_2=pvVarCapSetting2
PV_VAR_CAP_SETTING_3=pvVarCapSetting3
PV_VAR_CAP_SETTING_4=pvVarCapSetting4
PV_VAR_CAP_SETTING_5=pvVarCapSetting5
PV_V1_VOLT_WATT=pvV1VoltWatt
PV_V2_VOLT_WATT=pvV2VoltWatt
PV_P1_VOLT_WATT=pvP1VoltWatt
PVP2_VOLT_WATT=pvP2VoltWatt
