#JNDI properties for JNDI_LOGS
#UM Logs Active-Active Cluster
is.jndiAlias.description=Name Provider for JMS Logs
java.naming.factory.initial=com.pcbsys.nirvana.nSpace.NirvanaContextFactory
java.naming.provider.url=nsp\://um-logs-combined\:9000/
