PV_DG_NUMBER=Assign DG Number
PV_PRODUCTION_METER_1=PV Production Meter Number
PV_NOMINAL_VOLT=PV Nominal Volt 2
PV_VAR_PRIORITY=PV VAR Priority 2
PV_REC_INV_KVA=PV Rec Inv Kva 2
PV_POWER_FACTOR=PV Power Factor 2
PV_POWER_FACTOR_TYPE=PV Power Factor Type 2
PV_INV_SETTING_GENRTD=PV Inv Setting Genrtd 2
PV_INV_CAPACITY_REC=PV Inv Capacity Rec 2
PV_REC_INV_SETTING=PV REC INV SETTING 2
PV_VOLT_SET0=PV VOLT SET 0
PV_VOLT_SET1=PV VOLT SET 1
PV_VOLT_SET2=PV VOLT SET 2
PV_VOLT_SET3=PV VOLT SET 3
PV_VOLT_SET4=PV VOLT SET 4
PV_VOLT_SET5=PV VOLT SET 5
PV_VAR_CAP_SETTING0=PV VAR CAP SETTING 0
PV_VAR_CAP_SETTING1=PV VAR CAP SETTING 1
PV_VAR_CAP_SETTING2=PV VAR CAP SETTING 2
PV_VAR_CAP_SETTING3=PV VAR CAP SETTING 3
PV_VAR_CAP_SETTING4=PV VAR CAP SETTING 4
PV_VAR_CAP_SETTING5=PV VAR CAP SETTING 5
PV_V1_VOLT_WATT=PV V1 VOLT WATT
PV_V2_VOLT_WATT=PV V2 VOLT WATT
PV_P1_VOLT_WATT=PV P1 VOLT WATT
PV_P2_VOLT_WATT=PVP2 VOLT WATT
PV_QA_HOLD=PV QA HOLD
